services:
  # -------------------------
  # Auth Service
  # -------------------------
  auth-service:
    build: ./smart-waste-connect-backend/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./smart-waste-connect-backend/auth-service/.env
    volumes:
      - ./smart-waste-connect-backend/auth-service/logs:/app/logs # logs for Filebeat
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5001/auth/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network
  
  waste-service:
    build: ./smart-waste-connect-backend/waste-service
    container_name: waste-service
    ports:
    - "5002:5002"
    env_file:
      - ./smart-waste-connect-backend/waste-service/.env
    volumes:
      - ./smart-waste-connect-backend/waste-service/logs:/app/logs # logs for Filebeat
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5002/waste/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      auth-service:
        condition: service_healthy
      waste-service:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./smart-waste-connect-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./smart-waste-connect-frontend/.env.local
    depends_on:
      gateway:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

 