events {}

http {

  upstream auth_service {
    server auth-service:5001;
  }

  upstream waste_service {
    server waste-service:5002;
  }

  server {
    listen 80;

    # AUTH ROUTES
    location /auth/ {
      proxy_pass http://auth_service;
    }

    # WASTE ROUTES
    location /waste/ {
      proxy_pass http://waste_service;
    }

    # HEALTH CHECK
    location / {
      return 200 "API Gateway is running";
    }
  }
}